version: "3.5"

networks:
  default:
    name: eventstore-network

services:
  
  eventstore:
    image: ghcr.io/trogonstack/trogoneventstore:ci
    container_name: eventstore
    environment:
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_LOG_LEVEL=Information
      - EVENTSTORE_RUN_PROJECTIONS=None
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      
      # set certificates location
      - EVENTSTORE_CERTIFICATE_FILE=/etc/eventstore/certs/node/node.crt
      - EVENTSTORE_CERTIFICATE_PRIVATE_KEY_FILE=/etc/eventstore/certs/node/node.key
      - EVENTSTORE_TRUSTED_ROOT_CERTIFICATES_PATH=/etc/eventstore/certs/ca
    ports:
      - "2113:2113"
    volumes:
      - ./certs:/etc/eventstore/certs
      - type: volume
        source: eventstore-volume-data1
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs1
        target: /var/log/eventstore
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "--show-error", "--user", "admin:changeit", "--cacert", "/etc/eventstore/certs/ca/ca.crt", "https://localhost:2113/-/readiness"]
      interval: 1s
      timeout: 5s
      retries: 60
    restart: unless-stopped

volumes:
  eventstore-volume-data1:
  eventstore-volume-logs1:
