<Project>
    <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />

    <PropertyGroup>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <RootNamespace>KurrentDB.Client</RootNamespace>
        <AssemblyName>TrogonEventStore.Client</AssemblyName>
        <PackageId>TrogonEventStore.Client</PackageId>
    </PropertyGroup>

    <PropertyGroup>
        <PackageLicenseFile>LICENSE.md</PackageLicenseFile>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageProjectUrl>https://github.com/TrogonStack/TrogonEventStore-Client-Dotnet</PackageProjectUrl>
        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
        <PackageReleaseNotes>https://github.com/TrogonStack/TrogonEventStore-Client-Dotnet/releases</PackageReleaseNotes>
        <PackageTags>trogoneventstore eventstore client grpc</PackageTags>
        <Authors>Straw Hat, LLC</Authors>
        <Copyright>Copyright 2011-2025 Kurrent, Inc; Copyright 2026 Straw Hat, LLC</Copyright>
        <MinVerTagPrefix>v</MinVerTagPrefix>
        <RepositoryUrl>https://github.com/TrogonStack/TrogonEventStore-Client-Dotnet</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\..\LICENSE.md" Pack="true" PackagePath="\" />
        <None Include="..\..\README.md" Pack="true" PackagePath="\" />
    </ItemGroup>

    <ItemGroup>
<!--        <PackageReference Include="ConfigureAwaitChecker.Analyzer" Version="5.0.0.1">-->
<!--            <PrivateAssets>all</PrivateAssets>-->
<!--            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>-->
<!--        </PackageReference>-->
<!--        <PackageReference Include="Grpc.Tools" Version="$(GrpcToolsPackageVersion)">-->
<!--            <PrivateAssets>all</PrivateAssets>-->
<!--            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>-->
<!--        </PackageReference>-->
        <PackageReference Include="JetBrains.Annotations" Version="2024.3.0" PrivateAssets="All" />
        <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All"/>
        <PackageReference Include="MinVer" Version="3.0.0" PrivateAssets="All" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="$(ProjectName)" />
        <InternalsVisibleTo Include="$(ProjectName).Operations.Tests" />
        <InternalsVisibleTo Include="$(ProjectName).PersistentSubscriptions.Tests" />
        <InternalsVisibleTo Include="$(ProjectName).ProjectionManagement.Tests" />
        <InternalsVisibleTo Include="$(ProjectName).Streams.Tests" />
        <InternalsVisibleTo Include="$(ProjectName).UserManagement.Tests" />
        <InternalsVisibleTo Include="$(ProjectName).Extensions.OpenTelemetry" />
        <InternalsVisibleTo Include="$(ProjectName).Tests" />
        <InternalsVisibleTo Include="$(ProjectName).Common.Tests" />
        <InternalsVisibleTo Include="$(ProjectName).Tests.Common" />
    </ItemGroup>
</Project>
